version: '3.5'
services:
  web:
    build:
      context: .
      args:
        APP_ENV: 'development'
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: 'POSTGRES_URL'
